### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by SenLief** [lenmx/migu_music_downloader_wails#1]
点击下载选中无损后闪退

**Comment by lenmx** [comment]
@SenLief  是哪个版本的呀，要不试试最新的看看？

**Comment by SenLief** [comment]
> @SenLief 是哪个版本的呀，要不试试最新的看看？

最新的也闪退，win10的，只要点击下载无损的就会闪退。

**Comment by lenmx** [comment]
> > @SenLief 是哪个版本的呀，要不试试最新的看看？
> 
> 最新的也闪退，win10的，只要点击下载无损的就会闪退。

好的，手头没有 win10 电脑，晚点我修复一下

**Comment by lenmx** [comment]
@SenLief  修复了，下载最新的试试看
